env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
plugins:
  - promise
rules:
  arrow-parens:
    - error
    - as-needed
  camelcase:
    - error
    - properties: never
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-confusing-arrow:
    - error
    - allowParens: true
  prefer-arrow-callback: error
  prefer-const: error
  prefer-template: error
  promise/param-names: error
  promise/always-return: error
  promise/always-catch: error
  promise/catch-or-return: error
  promise/no-native: off
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  semi:
    - error
    - always
  template-curly-spacing:
    - error
    - never
